DROP TABLE IF EXISTS maps CASCADE;

CREATE TABLE maps(
  id SERIAL PRIMARY KEY NOT NULL,
  owner_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  coord_x DECIMAL NOT NULL,
  coord_y DECIMAL NOT NULL,
  zoom DECIMAL NOT NULL,
  description TEXT
);
